"""empty message

Revision ID: 082dc1f45b7f
Revises: 090eb10c05b4
Create Date: 2019-11-22 17:27:02.980454

"""

# revision identifiers, used by Alembic.
revision = '082dc1f45b7f'
down_revision = '090eb10c05b4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('id_firma', sa.Integer(), nullable=True))
    op.drop_constraint('User_Firma_id_fkey', 'User', type_='foreignkey')
    op.create_foreign_key(None, 'User', 'Firma', ['id_firma'], ['id'])
    op.drop_column('User', 'Firma_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('Firma_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.create_foreign_key('User_Firma_id_fkey', 'User', 'Firma', ['Firma_id'], ['id'])
    op.drop_column('User', 'id_firma')
    # ### end Alembic commands ###
