"""empty message

Revision ID: 090eb10c05b4
Revises: f9d4a3b94ed9
Create Date: 2019-11-22 17:25:36.570225

"""

# revision identifiers, used by Alembic.
revision = '090eb10c05b4'
down_revision = 'f9d4a3b94ed9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Skupina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_typ', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Group')
    op.add_column('User', sa.Column('Firma_id', sa.Integer(), nullable=True))
    op.add_column('User', sa.Column('id_skupina', sa.Integer(), nullable=True))
    op.drop_constraint('User_User_id_fkey', 'User', type_='foreignkey')
    op.create_foreign_key(None, 'User', 'Skupina', ['id_skupina'], ['id'])
    op.create_foreign_key(None, 'User', 'Firma', ['Firma_id'], ['id'])
    op.drop_column('User', 'User_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('User_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.create_foreign_key('User_User_id_fkey', 'User', 'Firma', ['User_id'], ['id'])
    op.drop_column('User', 'id_skupina')
    op.drop_column('User', 'Firma_id')
    op.create_table('Group',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Group_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_typ', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Group_pkey')
    )
    op.drop_table('Skupina')
    # ### end Alembic commands ###
