"""empty message

Revision ID: 0b8851fc67c9
Revises: None
Create Date: 2019-11-12 10:20:04.253455

"""

# revision identifiers, used by Alembic.
revision = '0b8851fc67c9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Firma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('ICO', sa.String(length=128), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ICO'),
    sa.UniqueConstraint('name')
    )
    op.create_table('PomocnaUserToGroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parent_id_firma', sa.Integer(), nullable=True),
    sa.Column('parent_id_pomocna', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id_firma'], ['Firma.id'], ),
    sa.ForeignKeyConstraint(['parent_id_pomocna'], ['PomocnaUserToGroup.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('pw_hash', sa.String(length=60), nullable=False),
    sa.Column('created_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remote_addr', sa.String(length=20), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('parent_id_pomocna', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id_pomocna'], ['PomocnaUserToGroup.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('Group')
    op.drop_table('PomocnaUserToGroup')
    op.drop_table('Firma')
    # ### end Alembic commands ###
