"""empty message

Revision ID: 87f05bbf6846
Revises: d65a87fc6249
Create Date: 2019-11-23 10:00:19.606209

"""

# revision identifiers, used by Alembic.
revision = '87f05bbf6846'
down_revision = 'd65a87fc6249'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Firma', 'created_ts')
    op.drop_column('Firma', 'updated_ts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Firma', sa.Column('updated_ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('Firma', sa.Column('created_ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
