"""empty message

Revision ID: f8cd92a7df1f
Revises: ff33413a8d55
Create Date: 2019-11-22 17:31:39.571398

"""

# revision identifiers, used by Alembic.
revision = 'f8cd92a7df1f'
down_revision = 'ff33413a8d55'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('cas_od_do', sa.Integer(), nullable=True))
    op.drop_constraint('User_id_cas_fkey', 'User', type_='foreignkey')
    op.create_foreign_key(None, 'User', 'Cas', ['cas_od_do'], ['id'])
    op.drop_column('User', 'id_cas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('id_cas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'User', type_='foreignkey')
    op.create_foreign_key('User_id_cas_fkey', 'User', 'Cas', ['id_cas'], ['id'])
    op.drop_column('User', 'cas_od_do')
    # ### end Alembic commands ###
