"""empty message

Revision ID: 1326569ad778
Revises: 1fb7c6da302
Create Date: 2020-01-04 13:56:59.058267

"""

# revision identifiers, used by Alembic.
revision = '1326569ad778'
down_revision = '1fb7c6da302'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Firma',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('ICO', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ICO'),
    sa.UniqueConstraint('name')
    )
    op.create_table('Skupina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('UnS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skupina_id', sa.Integer(), nullable=True),
    sa.Column('firma_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firma_id'], ['Firma.id'], ),
    sa.ForeignKeyConstraint(['skupina_id'], ['Skupina.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('pw_hash', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('created_ts', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('remote_addr', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key'),
    sa.UniqueConstraint('username', name='user_username_key')
    )
    op.drop_table('UnS')
    op.drop_table('User')
    op.drop_table('Skupina')
    op.drop_table('Firma')
    # ### end Alembic commands ###
