"""empty message

Revision ID: 971101b4e78e
Revises: 082dc1f45b7f
Create Date: 2019-11-22 17:28:00.001146

"""

# revision identifiers, used by Alembic.
revision = '971101b4e78e'
down_revision = '082dc1f45b7f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'id_firmy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('id_firmy', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
