"""empty message

Revision ID: c60b9f269953
Revises: f8cd92a7df1f
Create Date: 2019-11-22 17:34:17.584220

"""

# revision identifiers, used by Alembic.
revision = 'c60b9f269953'
down_revision = 'f8cd92a7df1f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Prava',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Skupina', sa.Column('typ_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Skupina', 'Prava', ['typ_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Skupina', type_='foreignkey')
    op.drop_column('Skupina', 'typ_id')
    op.drop_table('Prava')
    # ### end Alembic commands ###
