"""empty message

Revision ID: d65a87fc6249
Revises: c60b9f269953
Create Date: 2019-11-23 09:58:37.346285

"""

# revision identifiers, used by Alembic.
revision = 'd65a87fc6249'
down_revision = 'c60b9f269953'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Skupina', 'id_typ')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Skupina', sa.Column('id_typ', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
